# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdaptiveLearningPath', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseAlternate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caAlternate', to='AdaptiveLearningPath.Course')),
                ('coursePemilik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caPemilik', to='AdaptiveLearningPath.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Prerequisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursePemilik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpPemilik', to='AdaptiveLearningPath.Course')),
                ('coursePrereq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpPrereq', to='AdaptiveLearningPath.Course')),
            ],
        ),
    ]
