# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdaptiveLearningPath', '0002_course_alternative_course_prerequisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='alternative',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisit',
        ),
    ]
