# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdaptiveLearningPath', '0003_auto_20170802_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_CompletedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdaptiveLearningPath.Course')),
            ],
        ),
        migrations.CreateModel(
            name='User_Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdaptiveLearningPath.Concept')),
            ],
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='knowledge',
        ),
        migrations.AddField(
            model_name='user_knowledge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdaptiveLearningPath.UserStatus'),
        ),
        migrations.AddField(
            model_name='user_completedcourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdaptiveLearningPath.UserStatus'),
        ),
    ]
