# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdaptiveLearningPath', '0004_auto_20170802_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='waktuDiperlukan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edgeconcept',
            name='bobot',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
